"""Language-neutral implementation mapping and execution evidence profiles."""

from ucf.implementation_evidence.codec import (
    canonical_execution_environment_digest,
    canonical_implementation_evidence_digest,
    canonical_implementation_evidence_json,
    parse_execution_verification_request_json,
    parse_execution_verification_result_json,
    parse_implementation_mapping_request_json,
    parse_implementation_mapping_result_json,
)
from ucf.implementation_evidence.errors import (
    ImplementationEvidenceErrorCode,
    ImplementationEvidenceValidationError,
)
from ucf.implementation_evidence.identity import (
    derive_execution_verification_result_id,
    derive_implementation_mapping_result_id,
)
from ucf.implementation_evidence.models import (
    EXECUTION_VERIFICATION_CAPABILITY,
    EXECUTION_VERIFICATION_PROCEDURE_URI,
    EXECUTION_VERIFICATION_REQUEST_SCHEMA_URI,
    EXECUTION_VERIFICATION_RESULT_SCHEMA_URI,
    IMPLEMENTATION_EVIDENCE_VERSION,
    IMPLEMENTATION_MAPPING_CAPABILITY,
    IMPLEMENTATION_MAPPING_PROCEDURE_URI,
    IMPLEMENTATION_MAPPING_REQUEST_SCHEMA_URI,
    IMPLEMENTATION_MAPPING_RESULT_SCHEMA_URI,
    MAX_IMPLEMENTATION_BINDINGS,
    ExecutionEnvironment,
    ExecutionPortValue,
    ExecutionVerificationRequest,
    ExecutionVerificationResult,
    ImplementationBinding,
    ImplementationMappingRequest,
    ImplementationMappingResult,
    ImplementationMappingResultRef,
    ImplementationSource,
    OnboardingBundleBinding,
)
from ucf.implementation_evidence.projection import (
    ExecutionVerificationProjection,
    project_execution_verification,
)
from ucf.implementation_evidence.validation import (
    validate_execution_verification_request,
    validate_execution_verification_result,
    validate_execution_verification_result_structure,
    validate_implementation_mapping_request,
    validate_implementation_mapping_result,
    validate_implementation_mapping_result_structure,
)
from ucf.implementation_evidence.wire import (
    execution_verification_request_from_payload,
    execution_verification_request_to_payload,
    execution_verification_result_from_payload,
    execution_verification_result_to_payload,
    implementation_mapping_request_from_payload,
    implementation_mapping_request_to_payload,
    implementation_mapping_result_from_payload,
    implementation_mapping_result_to_payload,
)

__all__ = [
    "EXECUTION_VERIFICATION_CAPABILITY",
    "EXECUTION_VERIFICATION_PROCEDURE_URI",
    "EXECUTION_VERIFICATION_REQUEST_SCHEMA_URI",
    "EXECUTION_VERIFICATION_RESULT_SCHEMA_URI",
    "IMPLEMENTATION_EVIDENCE_VERSION",
    "IMPLEMENTATION_MAPPING_CAPABILITY",
    "IMPLEMENTATION_MAPPING_PROCEDURE_URI",
    "IMPLEMENTATION_MAPPING_REQUEST_SCHEMA_URI",
    "IMPLEMENTATION_MAPPING_RESULT_SCHEMA_URI",
    "MAX_IMPLEMENTATION_BINDINGS",
    "ExecutionEnvironment",
    "ExecutionPortValue",
    "ExecutionVerificationRequest",
    "ExecutionVerificationResult",
    "ExecutionVerificationProjection",
    "ImplementationBinding",
    "ImplementationMappingRequest",
    "ImplementationMappingResult",
    "ImplementationMappingResultRef",
    "ImplementationSource",
    "ImplementationEvidenceErrorCode",
    "ImplementationEvidenceValidationError",
    "OnboardingBundleBinding",
    "canonical_execution_environment_digest",
    "canonical_implementation_evidence_digest",
    "canonical_implementation_evidence_json",
    "derive_implementation_mapping_result_id",
    "derive_execution_verification_result_id",
    "execution_verification_request_from_payload",
    "execution_verification_request_to_payload",
    "execution_verification_result_from_payload",
    "execution_verification_result_to_payload",
    "implementation_mapping_request_from_payload",
    "implementation_mapping_request_to_payload",
    "implementation_mapping_result_from_payload",
    "implementation_mapping_result_to_payload",
    "parse_execution_verification_request_json",
    "parse_execution_verification_result_json",
    "parse_implementation_mapping_request_json",
    "parse_implementation_mapping_result_json",
    "project_execution_verification",
    "validate_execution_verification_request",
    "validate_execution_verification_result",
    "validate_execution_verification_result_structure",
    "validate_implementation_mapping_request",
    "validate_implementation_mapping_result",
    "validate_implementation_mapping_result_structure",
]
