"""Generate the deterministic public JSON Schema for UCF source specs."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Annotated, Any

from pydantic import Field, TypeAdapter

from ucf.models.action import ActionSpec
from ucf.models.component import ComponentSpec
from ucf.models.event import EventSpec
from ucf.models.invariant import InvariantSpec
from ucf.models.protocol import ProtocolSpec
from ucf.models.usecase import UseCaseSpec

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = (
    REPOSITORY_ROOT / "src" / "ucf" / "schemas" / "spec" / "v1" / "schema.json"
)
SCHEMA_ID = "urn:ucf:schema:spec:v1"
SCHEMA_VERSION = "1"
SPEC_DEFINITIONS = (
    "ActionSpec",
    "EventSpec",
    "ComponentSpec",
    "ProtocolSpec",
    "UseCaseSpec",
    "InvariantSpec",
)

SpecDocument = Annotated[
    ActionSpec
    | EventSpec
    | ComponentSpec
    | ProtocolSpec
    | UseCaseSpec
    | InvariantSpec,
    Field(discriminator="kind"),
]


def build_schema() -> dict[str, Any]:
    """Build the source schema from the authoritative runtime models."""

    schema = TypeAdapter(SpecDocument).json_schema(by_alias=True)
    schema.update(
        {
            "$comment": (
                "Generated by tools/generate_spec_schema.py; do not edit by hand."
            ),
            "$id": SCHEMA_ID,
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "description": (
                "Strict source schema for the six current UCF specification "
                "kinds. Execution capabilities are documented separately."
            ),
            "title": "UCF source specification schema v1",
            "x-ucf-schema-version": SCHEMA_VERSION,
        }
    )
    _apply_runtime_constraints(schema)
    return schema


def _apply_runtime_constraints(schema: dict[str, Any]) -> None:
    definitions = schema["$defs"]

    # parse_spec requires the discriminator before selecting a model, while
    # individual Pydantic models retain a default for direct Python callers.
    for definition_name in SPEC_DEFINITIONS:
        definition = definitions[definition_name]
        required = definition.setdefault("required", [])
        if "kind" not in required:
            required.insert(0, "kind")

    # Pydantic model validators express these constraints at runtime but do not
    # emit equivalent JSON Schema keywords automatically.
    step_definition = definitions["StepDef"]
    for field_name in ("when", "skip_if"):
        for option in step_definition["properties"][field_name]["anyOf"]:
            if option.get("type") == "string":
                option["pattern"] = r"\S"
    step_definition["not"] = {
        "properties": {
            "when": {"type": "string"},
            "skip_if": {"type": "string"},
        },
        "required": ["when", "skip_if"],
    }


def render_schema() -> str:
    return json.dumps(
        build_schema(),
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
    ) + "\n"


def _parse_args(arguments: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate or check the published UCF source JSON Schema."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Schema output path (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero instead of writing when the checked-in schema is stale.",
    )
    return parser.parse_args(arguments)


def main(arguments: list[str] | None = None) -> int:
    args = _parse_args(arguments)
    rendered = render_schema()
    output: Path = args.output

    if args.check:
        if not output.exists():
            print(f"Schema is missing: {output}")
            return 1
        if output.read_text(encoding="utf-8") != rendered:
            print(f"Schema is stale: {output}")
            return 1
        print(f"Schema is current: {output}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    print(f"Wrote schema: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
