"""Versioned language-neutral out-of-process adapter protocol."""

from ucf.adapter_protocol.codec import (
    decode_request_frame,
    decode_response_frame,
    encode_frame,
)
from ucf.adapter_protocol.dispatcher import (
    AdapterDispatcher,
    AdapterRequestCancelled,
    CancellationSignal,
    RequestContext,
    SessionState,
)
from ucf.adapter_protocol.errors import (
    AdapterProtocolError,
    ErrorCategory,
    ProtocolCode,
)
from ucf.adapter_protocol.models import (
    ADAPTER_PROTOCOL_VERSION,
    MAX_FRAME_BYTES,
    MAX_PENDING_REQUESTS,
    MAX_REQUESTS_PER_SESSION,
    MAX_RETAINED_STDERR_BYTES,
    AdapterPayload,
    CancelNotification,
    CancelParams,
    CapabilityRequest,
    CapabilitySelection,
    ErrorData,
    ErrorObject,
    ErrorResponse,
    InitializeParams,
    InitializeResult,
    Method,
    OperationKind,
    OperationParams,
    OperationResult,
    Request,
    ShutdownParams,
    ShutdownResult,
    SuccessResponse,
)
from ucf.adapter_protocol.process import (
    AdapterCall,
    AdapterProcess,
    ProcessState,
    ProcessTimeouts,
)
from ucf.adapter_protocol.profile_values import (
    MAX_PROFILE_VALUE_DEPTH,
    ir_value_to_json_profile,
    json_profile_to_ir_value,
)
from ucf.adapter_protocol.server import run_stdio_server

__all__ = [
    "ADAPTER_PROTOCOL_VERSION",
    "MAX_FRAME_BYTES",
    "MAX_PENDING_REQUESTS",
    "MAX_PROFILE_VALUE_DEPTH",
    "MAX_REQUESTS_PER_SESSION",
    "MAX_RETAINED_STDERR_BYTES",
    "AdapterDispatcher",
    "AdapterCall",
    "AdapterPayload",
    "AdapterProcess",
    "AdapterProtocolError",
    "AdapterRequestCancelled",
    "CancellationSignal",
    "CancelNotification",
    "CancelParams",
    "CapabilityRequest",
    "CapabilitySelection",
    "ErrorCategory",
    "ErrorData",
    "ErrorObject",
    "ErrorResponse",
    "InitializeParams",
    "InitializeResult",
    "Method",
    "OperationKind",
    "OperationParams",
    "OperationResult",
    "ProtocolCode",
    "ProcessState",
    "ProcessTimeouts",
    "Request",
    "RequestContext",
    "SessionState",
    "ShutdownParams",
    "ShutdownResult",
    "SuccessResponse",
    "decode_request_frame",
    "decode_response_frame",
    "encode_frame",
    "ir_value_to_json_profile",
    "json_profile_to_ir_value",
    "run_stdio_server",
]
